SistemaCarros/Clientes/urls.py
from . import views
from django.urls import path
from django.conf.urls.i18n import i18n_patterns

app_name='Clientes'

urlpatterns=[
    path('',views.list_clientes,name='clientes_list'),
    path('add',views.create_clientes.as_view(),name='clientes_add'),
    path('edit/<int:pk>',views.edit_clientes.as_view(),name='clientes_edit'),
    path('<int:pk>/',views.detail_clientes.as_view(),name='clientes_detail'),
    path('delete/<int:pk>',views.eliminar_cliente.as_view(),name='clientes_delete'),
]

SistemaCarros/Foto/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


app_name='Foto'

urlpatterns=[
    path('add',views.create_Foto,name='foto')
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SistemaCarros/SistemaCarros/urls.py
from django.contrib import admin
from django.urls import path, include
from Usuarios import views as user_views
from Usuarios.views import PasswordsChangeView, EditProfilePageView
from . import views as sistema_views, views
from django.contrib.auth import views as authentication_views, logout
from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('carros/',include('carros.urls')),
    path('cliente-empresas/',include('ClienteEmpresas.urls')),
    path('clientes/', include('Clientes.urls')),
    #path('presupuestos/', include('Presupuestos.urls')),
    path('estimates/', include('Presupuestos.urls')),
    path('mano-obra/', include('ManoObra.urls')),
    path('parte/', include('Parte.urls')),
    path('informacion-tiendas/', include('InformacionTiendas.urls')),
    path('pagos/', include('Pagos.urls')),
    path('reports/', include('ReporteGanancias.urls')),
    path('foto/', include('Foto.urls')),
    path('detalle/', include('Detalle.urls')),
    path('invoices/', include('invoices.urls')),
    path('technicians/', include('tecnicos.urls')),
    # path('inventory/', include('inventory.urls')),
    #Dashboard
    #path('nuevo_cliente',user_views.nuevo_cliente, name='nuevo_cliente'),


    #Authentications
    path('registro/',user_views.registro,name='registro'),
    path('login/',authentication_views.LoginView.as_view(template_name='Usuarios/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='Usuarios/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
    path('profile/change-password/',PasswordsChangeView.as_view(template_name='Usuarios/change-password.html'),name='change-password'),
    path('password_success',user_views.password_success,name="password_success"),
    path('profile/<int:pk>/edit-profile/',EditProfilePageView.as_view(),name='edit-profile'),

    #RichFields
    path('djrichtextfield/', include('djrichtextfield.urls')),

    #search
    path('search/',sistema_views.search, name='search'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        ) 

SistemaCarros/dashboard/urls.py
from . import views
from django.urls import path

app_name='dashboard'

urlpatterns=[
    #/dashboard/
    path('',views.dashboard,name='dashboard'),

]

SistemaCarros/Clientes/models.py
from datetime import datetime

from django.db import models
from ckeditor.fields import RichTextField




class Clientes(models.Model):
    tipo = models.CharField(max_length=200)
    TITLE = (
        ('Mrs.', 'Mrs.'),
        ('Miss', 'Miss'),
        ('Mr.', 'Mr.'),
    )
    corporacion=models.CharField(max_length=200,blank=True)
    titulo = models.CharField(max_length=200, choices=TITLE,default='Mr.')
    nombre = models.CharField(max_length=200, blank=True)
    apellido = models.CharField(max_length=200,blank=True)
    telefono = models.IntegerField(blank=True, null=True)
    tel = models.IntegerField(blank=True, null=True)
    alternativeContactName = models.CharField(blank=True, null=True, max_length=200)
    alternativeContactPhoneNumber = models.IntegerField(blank=True, null=True, max_length=200)
    fax = models.IntegerField(blank=True, null=True)
    correo = models.EmailField(max_length=200,blank=True, null=True)
    website=models.URLField(max_length=200,blank=True, null=True)
    social_media=models.CharField(max_length=200,blank=True, null=True)
    representative=models.CharField(max_length=200,blank=True, null=True)
    nameRepresentative=models.CharField(max_length=200,blank=True, null=True)
    department=models.CharField(max_length=10,blank=True, null=True)
    phoneRepresentative = models.IntegerField(max_length=10, blank=True, null=True)
    emailRepresentative = models.CharField(max_length=20, blank=True, null=True)
    notesRepresentative = models.CharField(max_length=200, blank=True, null=True)
    # pais = models.CharField(max_length=200,blank=True, null=True)
    taxId=models.IntegerField(max_length=10,blank=True, null=True)
    ciudad=models.CharField(max_length=255,blank=True, null=True)
    estado=models.CharField(max_length=255,blank=True, null=True)
    zip=models.CharField(max_length=255,blank=True, null=True)
    fecha_registro = models.DateTimeField(default=datetime.now,blank=True, null=True)



    def __str__(self):
        return f'{self.nombre} {self.apellido}'

SistemaCarros/Clientes/forms.py
from django import forms
from Clientes.models import Clientes
from django.utils.translation import gettext_lazy as _



# PAIS = (
#     ('United States',  _('United States')),
#     ('Canada', _('Canada')),
#     ('Other', _('Other')),
# )

TIPO = (
    ('corporative', _('Corporative')),
    ('person', _('Person')),
)





class ClientesForm(forms.ModelForm):

    tipo = forms.ChoiceField(
        choices=TIPO,
        widget=forms.RadioSelect(attrs={'class':'custom-radio-list', 'onclick':'showForm(this)'}),

    )
    #
    # pais = forms.ChoiceField(
    #     choices=PAIS,
    #     widget=forms.RadioSelect(attrs={'class':'custom-radio-list'}),
    #
    # )


    class Meta:
        model = Clientes
        fields = ['titulo','tipo','nombre', 'apellido', 'telefono', 'alternativeContactName', 'alternativeContactPhoneNumber','fax', 'correo', 'taxId',
                  'ciudad','estado','zip','corporacion', 'website','social_media','department','tel',
                   'representative','nameRepresentative','phoneRepresentative','emailRepresentative','notesRepresentative']
        exclude = ['fecha_registro']
        widgets = {

            'titulo': forms.Select(
                attrs={
                    'class': 'form-select'
                }
            ),
            'corporacion': forms.TextInput(
                # required=True,
                attrs={
                    'class': 'form-control',
                    # 'required': True,
                }
            ),
            'tel': forms.TextInput(
                # required=True,
                attrs={
                    'class': 'form-control',
                    # 'required': True,

                }
            ),
            'nombre': forms.TextInput(
                # required=True,
                attrs={
                    'class': 'form-control',
                    # 'required': True,


                }
            ),
            'apellido': forms.TextInput(
                # required=True,
                attrs={
                    'class': 'form-control',
                    # 'required': True,
                }
            ),
            'telefono': forms.TextInput(
                # required=True,
                attrs={
                    'class': 'form-control',
                    # 'required': True,
                }
            ),
            'alternativeContactName': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'alternativeContactPhoneNumber': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'department': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'phoneRepresentative': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'emailRepresentative': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'notesRepresentative': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),

            'fax': forms.TextInput(
                attrs={
                    'class': 'form-control',

                }
            ),
            'correo': forms.TextInput(
                # required=True,
                attrs={
                    'class': 'form-control',
                    # 'required': True,
                }
            ),

            'website': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'social_media': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),

            'representative': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'nameRepresentative': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),

            'taxId': forms.TextInput(
                # required=True,
                attrs={
                    'class': 'form-control',
                    # 'required': True,
                }
            ),
            'ciudad': forms.TextInput(
                # required=True,
                attrs={
                    'class': 'form-control',
                    # 'required': True,
                }
            ),
            'estado': forms.TextInput(
                # required=True,
                attrs={
                    'class': 'form-control',
                    # 'required': True,
                }
            ),
            'zip': forms.TextInput(
                # required=True,
                attrs={
                    'class': 'form-control',
                    # 'required': True,
                }
            ),
            'fecha_registro': forms.DateInput(
                attrs={
                    'class': 'form-control',
                }
            ),

        }

class DateRangeForm(forms.Form):
    start_date = forms.DateField()
    end_date = forms.DateField()

SistemaCarros/Clientes/views.py
from datetime import datetime

from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect

#language


# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView
from requests import request

from .forms import ClientesForm, DateRangeForm
from .models import Clientes
from django.contrib import messages



def list_clientes(request):

    from django.utils.translation import gettext as _
    # user_language='es'
    # translation.activate(user_language)
    # request.session[translation.LANGUAGE_SESSION_KEY]=user_language
    # if translation.LANGUAGE_SESSION_KEY in request.session:
    #     del request.session[translation.LANGUAGE_SESSION_KEY]
    # title=_('Homepage')
    if request.method == 'POST':
        fromdate=request.POST.get('fromdate')
        todate = request.POST.get('todate')
        searchresult = Clientes.objects.filter(fecha_registro__range=(fromdate, todate))
        return render(request,'Clientes/clientes-list.html',{'clientes':searchresult})

    else:
        displaydata = Clientes.objects.all()
    return render(request, 'Clientes/clientes-list.html', {'clientes': displaydata})


    # if request.method == 'POST':
    #     fromdate=request.POST.get('fromdate')
    #     todate = request.POST.get('todate')
    #     searchresult=Clientes.objects.raw('select nombre from Clientes where joindate between "'+fromdate+'" and "'+todate+'"')
    #     return render(request,'Clientes/clientes-list.html',{'clientes':searchresult})
    #
    # else:
    #     displaydata = Clientes.objects.all()
    # return render(request, 'Clientes/clientes-list.html', {'clientes': displaydata})



   #



#
# def list_clientes(request):
#
#     if request.method == 'POST':
#         form = DateRangeForm(request.POST)
#         # fromdate=request.POST.get('start_date')
#         # todate=request.POST.get('end_date')
#
#         if form.is_valid():
#             qs = Clientes.objects.filter(fecha_registro__range=(
#                 form.cleaned_data['start_date'],
#                 form.cleaned_data['end_date']
#             ))
#             return redirect('Clientes:clientes_list')
#     else:
#         clientes = Clientes.objects.all()
#         form=DateRangeForm()
#         return render(request,'Clientes/clientes-list.html',{'form':form, 'clientes':clientes})


#
# class list_clientes(ListView):
#     model=Clientes
#     template_name = 'Clientes/clientes-list.html'
#     context_object_name='clientes'
#     queryset=Clientes.objects.all()
#
#     #adicional
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['now'] = timezone.now()
#         return context





class detail_clientes(DetailView):
    template_name = 'Clientes/clientes-detail.html'
    queryset=Clientes.objects.all()
    context_object_name = 'clientes'



class create_clientes(SuccessMessageMixin,CreateView):
    model=Clientes
    form_class = ClientesForm
    template_name='Clientes/clientes-add.html'
    success_url=reverse_lazy('Clientes:clientes_list')
    success_message = "New customer was created successfully"



class edit_clientes(UpdateView):
    model=Clientes
    form_class = ClientesForm
    template_name='Clientes/clientes-add.html'
    success_url=reverse_lazy('Clientes:clientes_list')

class eliminar_cliente(DeleteView):
    model=Clientes
    success_url=reverse_lazy('Clientes:clientes_list')
    context_object_name = 'clientes'

SistemaCarros/Clientes/templates/Clientes/clientes-detail.html
{% extends 'SistemaCarros/base.html' %}
{% load widget_tweaks %}
{% load i18n %}



{% block content %}


            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">

                <div class="page-content">
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box d-flex align-items-center justify-content-between">
                                    <h4 class="mb-0">{% trans "Customers" %}</h4>

                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="{% url 'dashboard:dashboard' %}">Dashboard</a></li>
                                            <li class="breadcrumb-item active">{% trans "Customers" %}</li>
                                        </ol>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <!-- end page title -->


                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">

                                                            <h4>{{ clientes.nombre }} {{ clientes.apellido }}</h4>
                                                            <h4>{{ clientes.corporacion }}</h4>
                                                            <hr>
                                                            <p><b>{% trans "Phone 1" %}: </b>{{ clientes.telefono }}</p>
                                                            <p><b>{% trans "Phone 2" %} </b>{{ clientes.tel }}</p>
                                                            <p><b>FAX: </b>{{ clientes.fax }}</p>
                                                            <p><b>{% trans "E-mail" %}: </b>{{ clientes.correo }}</p>
                                                            <p><b>{% trans "Website" %}: </b>{{ clientes.website }}</p>
                                                            <p><b>{% trans "Social media" %}: </b>{{ clientes.social_media }}</p>
                                                            <p><b>{% trans "Social media 2" %}: </b>{{ clientes.social_media2 }}</p>
                                                            <p><b>{% trans "Social media 3" %}: </b>{{ clientes.social_media3 }}</p>
                                                            <p><b>{% trans "Alternative contact 1" %}: </b>{{ clientes.contacto_alternativo }}</p>
                                                            <p><b>{% trans "Country" %}: </b>{{ clientes.pais }}</p>
                                                            <p><b>{% trans "Address" %}: </b>{{ clientes.direccion }}</p>
                                                            <p><b>{% trans "City / Town" %}: </b>{{ clientes.ciudad }}</p>
                                                            <p><b>{% trans "State" %}: </b>{{ clientes.estado }}</p>
                                                            <p><b>{% trans "Zip" %}: </b>{{ clientes.zip }}</p>
                                                            <p><b>{% trans "Registration date" %}: </b>{{ clientes.fecha_registro }}</p>

                                </div>
                            </div> <!-- end col -->
                        </div> <!-- end row -->



                    </div> <!-- container-fluid -->
                </div>
                <!-- End Page-content -->
            </div>

{% endblock %}

SistemaCarros/Clientes/templates/Clientes/clientes-list.html
{% extends 'SistemaCarros/base.html' %}
{% load widget_tweaks %}
{% block content %}
{% load i18n %}
<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="main-content">
   <div class="page-content">
      <div class="container-fluid">

         <!-- start page title -->
         <div class="row">
            <div class="col-12">
               <div class="page-title-box d-flex align-items-center justify-content-between">
                  <h4 class="mb-0">{% trans "Customers" %}</h4>

                  <div class="page-title-right">
                     <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{% url 'dashboard:dashboard' %}">Dashboard</a></li>
                        <li class="breadcrumb-item active">{% trans "Customers" %}</li>
                     </ol>
                  </div>
               </div>
            </div>
         </div>
         <!-- end page title -->
         <div class="row">
            <div class="col-12">
               <form method="post">
                  {% csrf_token %}
                  <div class="d-flex justify-content-between">
                     <a href="{% url 'Clientes:clientes_add' %}">
                     <button type="button" class="btn btn-success mb-3 waves-effect waves-light" onclick="addNewCustomer()">{% trans "Add new" %}</button>
                     </a>
                     <div class="col-md-6 mb-3 d-flex align-items-center justify-content-end">
                        <div class="span-container d-flex">
                           <input type="date" name="fromdate" class="form-control" data-date-inline-picker="true">
                           <input type="date" name="todate" class="form-control" data-date-inline-picker="true">
                           <input type="submit" value="{% trans 'Search' %}" class="btn btn-secondary">
                           <!--                                                <input type="text" name="daterange" value="12/01/2021 - 12/31/2021" class="form-control" id="id_date_range"/>-->
                        </div>
                        <!--                                                <input type="text" name="daterange" value="12/01/2021 - 12/31/2021" class="form-control" id="id_date_range"/>-->
                     </div>
                  </div>
                  <div class="card">
                     <div class="card-body">
                        {% if clientes %}
                        <div class="table-rep-plugin">
                           <div class="table-responsive mb-0" data-pattern="priority-columns">
                              <table id="tech-companies-1" class="table">
                                 <thead>
                                    <tr>
                                       <th>{% trans "Customer ID" %}</th>
                                       <th data-priority="1">{% trans "Name" %}</th>
                                       <th data-priority="1">{% trans "Company name" %}</th>
                                       <th data-priority="1">{% trans "Customer type" %}</th>
                                       <!--                                                        <th data-priority="1">Vehicles</th>-->
                                       <th>{% trans "Register since" %}</th>
                                       <th data-priority="1">{% trans "Actions" %}</th>
                                    </tr>
                                 </thead>
                                 <tbody>
                                    {% for cliente in clientes %}
                                    <tr>
                                       <td>{{cliente.id}}</td>

                                       <td>{{cliente.nombre}}</td>
                                       <td>{{cliente.corporacion}}</td>
                                       <td>{{cliente.tipo}}</td>
                                       <td>{{cliente.fecha_registro}}</td>
                                       <td>
                                          <!--                                                                <a data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="uil-search-alt"></i></a>-->
                                          <a href="{% url 'Clientes:clientes_detail' cliente.id%}">{% trans "Detail" %}</a>
                                       </td>
                                       <td>
                                          <a href="{% url 'Clientes:clientes_edit' cliente.id%}">{% trans "Edit" %}</a>
                                       </td>
                                       <td>
                                          <a href="{% url 'Clientes:clientes_delete' cliente.id%}" class="text-danger">{% trans "Delete" %}</a>
                                       </td>
                                    </tr>
                                    {% endfor %}
                                 </tbody>
                              </table>
                           </div>
                        </div>
                        {% endif %}
                     </div>
               </form>
               </div>
            </div>
            <!-- end col -->
         </div>
         <!-- end row -->
      </div>
      <!-- container-fluid -->
   </div>
   <!-- End Page-content -->
</div>
{% endblock %}

SistemaCarros/Clientes/templates/Clientes/clientes_confirm_delete.html
{% extends 'SistemaCarros/base.html' %}
{% block content %}
{% load i18n %}

            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">

                <div class="page-content">
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box d-flex align-items-center justify-content-between">
                                    <h4 class="mb-0">{% trans "Customers" %}</h4>

                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="{% url 'dashboard:dashboard' %}">Dashboard</a></li>
                                            <li class="breadcrumb-item active">{% trans "Customers" %}</li>
                                        </ol>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <!-- end page title -->


                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">



                                        <form method="post">{% csrf_token %}
                                            <p>{% trans "Are you sure you want to delete" %} "{{ clientes.nombre }} {{ clientes.apellido }}"?</p>
                                            <button class="btn btn-danger mb-3" type="submit">{% trans "Delete" %}</button>
                                        </form>



                                    </div>
                                </div>
                            </div> <!-- end col -->
                        </div> <!-- end row -->



                    </div> <!-- container-fluid -->
                </div>
                <!-- End Page-content -->
            </div>




{% endblock %}