SistemaCarros/Foto/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


app_name='Foto'

urlpatterns=[
    path('add',views.create_Foto,name='foto')
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SistemaCarros/SistemaCarros/urls.py
from django.contrib import admin
from django.urls import path, include
from Usuarios import views as user_views
from Usuarios.views import PasswordsChangeView, EditProfilePageView
from . import views as sistema_views, views
from django.contrib.auth import views as authentication_views, logout
from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('carros/',include('carros.urls')),
    path('cliente-empresas/',include('ClienteEmpresas.urls')),
    path('clientes/', include('Clientes.urls')),
    #path('presupuestos/', include('Presupuestos.urls')),
    path('estimates/', include('Presupuestos.urls')),
    path('mano-obra/', include('ManoObra.urls')),
    path('parte/', include('Parte.urls')),
    path('informacion-tiendas/', include('InformacionTiendas.urls')),
    path('pagos/', include('Pagos.urls')),
    path('reports/', include('ReporteGanancias.urls')),
    path('foto/', include('Foto.urls')),
    path('detalle/', include('Detalle.urls')),
    path('invoices/', include('invoices.urls')),
    path('technicians/', include('tecnicos.urls')),
    # path('inventory/', include('inventory.urls')),
    #Dashboard
    #path('nuevo_cliente',user_views.nuevo_cliente, name='nuevo_cliente'),


    #Authentications
    path('registro/',user_views.registro,name='registro'),
    path('login/',authentication_views.LoginView.as_view(template_name='Usuarios/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='Usuarios/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
    path('profile/change-password/',PasswordsChangeView.as_view(template_name='Usuarios/change-password.html'),name='change-password'),
    path('password_success',user_views.password_success,name="password_success"),
    path('profile/<int:pk>/edit-profile/',EditProfilePageView.as_view(),name='edit-profile'),

    #RichFields
    path('djrichtextfield/', include('djrichtextfield.urls')),

    #search
    path('search/',sistema_views.search, name='search'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        ) 

SistemaCarros/dashboard/urls.py
from . import views
from django.urls import path

app_name='dashboard'

urlpatterns=[
    #/dashboard/
    path('',views.dashboard,name='dashboard'),

]

SistemaCarros/tecnicos/urls.py
from . import views
from django.urls import path

app_name='tecnicos'

urlpatterns=[
    path('',views.tecnico_list,name='list_tecnicos'),
    path('add',views.addTecnico.as_view(),name='add_tecnicos'),
    path('edit/<int:pk>', views.edit_inventory.as_view(), name='edit_tecnicos'),
    path('delete/<int:pk>', views.eliminar_tecnicos.as_view(), name='eliminar_tecnicos'),
    path('<int:pk>/', views.tecnicos_detail.as_view(), name='tecnicos_detail'),
    # path('edit',views.addPart.as_view(),name='add-part'),

]

SistemaCarros/tecnicos/models.py
from datetime import datetime

from django.db import models

# Create your models here.



class Tecnicos(models.Model):


    nombreTecnico= models.CharField(max_length=255,blank=True)
    apellidoTecnico= models.CharField(max_length=255,blank=True)
    emailTecnico=models.EmailField(max_length=255,blank=True)
    telTecnico=models.CharField(max_length=11,blank=True)
    telTecnico2=models.CharField(max_length=11,blank=True)
    notasTecnico=models.TextField(max_length=255,blank=True)
    fecha_registro = models.DateTimeField(default=datetime.now)


    def __str__(self):
        return f'{self.apellidoTecnico}'

SistemaCarros/tecnicos/forms.py
from django import forms
from django.forms import formset_factory

from tecnicos.models import Tecnicos


class TecnicosForm(forms.ModelForm):

    class Meta:
        model = Tecnicos
        fields = ['nombreTecnico', 'apellidoTecnico', 'emailTecnico', 'telTecnico', 'telTecnico2', 'notasTecnico']
        exclude = ['fecha_registro']
        widgets = {
            'nombreTecnico': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'apellidoTecnico': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'emailTecnico': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'telTecnico': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'telTecnico2': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'notasTecnico': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'fecha_registro': forms.DateInput(
                attrs={
                    'class': 'form-control',
                }
            ),
        }

class DateRangeForm(forms.Form):
    start_date = forms.DateField()
    end_date = forms.DateField()

SistemaCarros/tecnicos/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import formset_factory, modelform_factory
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, UpdateView, CreateView, ListView, FormView, DeleteView, DetailView

from Clientes.forms import ClientesForm
from Parte.forms import ParteForm
from tecnicos.forms import TecnicosForm
from tecnicos.models import Tecnicos



def tecnico_list(request):

    if request.method == 'POST':
        fromdate=request.POST.get('fromdate')
        todate = request.POST.get('todate')
        searchresult = Tecnicos.objects.filter(fecha_registro__range=(fromdate, todate))
        return render(request,'tecnicos/list.html',{'tecnicos':searchresult})

    else:
        disreplaydata = Tecnicos.objects.all()
    return render(request, 'tecnicos/list.html', {'tecnicos': disreplaydata})



class tecnicoIndex(ListView):
    model=Tecnicos
    template_name = 'tecnicos/list.html'
    context_object_name='tecnicos'
    queryset=Tecnicos.objects.all()

class addTecnico(SuccessMessageMixin,CreateView):
    model=Tecnicos
    form_class=TecnicosForm
    template_name='tecnicos/add.html'
    success_url=reverse_lazy('tecnicos:list_tecnicos')
    success_message = "%(nombreTecnico)s this is was created successfully"


class edit_inventory(UpdateView):
    model=Tecnicos
    form_class = TecnicosForm
    template_name='tecnicos/add.html'
    success_url=reverse_lazy('tecnicos:list_tecnicos')



class eliminar_tecnicos(DeleteView):
    model=Tecnicos
    success_url=reverse_lazy('tecnicos:list_tecnicos')
    context_object_name = 'tecnico'

class tecnicos_detail(DetailView):
    template_name = 'tecnicos/tecnicos-detail.html'
    queryset=Tecnicos.objects.all()
    context_object_name = 'tecnico'

SistemaCarros/tecnicos/templates/tecnicos/add.html
{% extends 'SistemaCarros/base.html' %}
{% load widget_tweaks %}



{% block content %}



            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">

                <div class="page-content">
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box d-flex align-items-center justify-content-between">
                                    <h4 class="mb-0">Adding...</h4>

                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">The Shop</a></li>
                                            <li class="breadcrumb-item"><a href="technicians.html">Technicians</a></li>
                                            <li class="breadcrumb-item active">Add</li>
                                        </ol>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <!-- end page title -->


                        <div class="row">
                            <div class="col-xl-8">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="card-title mb-3">Technician information</h4>
                                        <form method="POST" class="needs-validation" novalidate>
                                            {% csrf_token %}
                                            <div class="row mb-3 align-items-center">
                                                <div class="row mb-3">

                                                    <div class="col-md-6 only-person">
                                                        <div class="mb-3">
                                                            <label for="verticalnav-firstname-input">First name</label>
                                                            {{form.nombreTecnico}}
                                                            <div class="invalid-feedback">
                                                                Please provide the first name.
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6 only-person">
                                                        <div class="mb-3">
                                                            <label class="form-label" for="verticalnav-lastname-input">Last name</label>
                                                            {{form.apellidoTecnico}}
                                                            <div class="invalid-feedback">
                                                                Please provide the last name.
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="row mb-3">
                                                    <div class="col-md-4">
                                                        <div class="mb-3">
                                                            <label class="form-label" for="validationCustom08">Phone 1</label>
                                                            {{form.telTecnico}}
                                                            <div class="invalid-feedback">
                                                                Please provide a phone number.
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <div class="mb-3">
                                                            <label class="form-label" for="validationCustom09">Phone 2</label>
                                                            {{form.telTecnico2}}
                                                            <div class="invalid-feedback">
                                                                Please provide a phone number.
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <div class="mb-3">
                                                            <label class="form-label" for="validationCustom11">E-mail</label>
                                                            {{form.emailTecnico}}
                                                            <div class="invalid-feedback">
                                                                Please provide an e-mail.
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="mb-3">
                                                            <label class="form-label">Notes</label>
                                                            {{form.notasTecnico}}
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="mb-3">
                                                            {{ form.fecha_registro }}
                                                        </div>
                                                    </div>
                                                </div>


                                            </div>

                                            <!-- <div class="row mb-5">
                                                <div class="col-md-4">
                                                    <div class="form-check">
                                                        <input class="form-check-input" type="checkbox" id="autoSizingCheck2">
                                                        <label class="form-check-label" for="autoSizingCheck2">
                                                          Brought by client
                                                        </label>
                                                      </div>
                                                </div>
                                            </div> -->


                                            <button class="btn btn-primary mb-3" type="submit">Save</button>
                                        </form>
                                    </div>
                                </div>
                                <!-- end card -->
                            </div> <!-- end col -->


                        </div>
                        <!-- end row -->



                    </div> <!-- container-fluid -->
                </div>
                <!-- End Page-content -->


                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-6">
                                <script>document.write(new Date().getFullYear())</script> © The Shop.
                            </div>
                            <div class="col-sm-6">
                                <div class="text-sm-end d-none d-sm-block">

                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
            <!-- end main content-->

        </div>
        <!-- END layout-wrapper -->
{% endblock %}

SistemaCarros/tecnicos/templates/tecnicos/list.html
{% extends 'SistemaCarros/base.html' %}
{% load widget_tweaks %}
{% block content %}
<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="main-content">
<div class="page-content">
   <form method="post">
      {% csrf_token %}
      <div class="container-fluid">
         <!-- start page title -->
         <div class="row">
            <div class="col-12 mb-3">
               <div class="page-title-box d-flex align-items-center justify-content-between">
                  <h4 class="mb-0">Technicians</h4>
                  <div class="page-title-right">
                     <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">The Shop</a></li>
                        <li class="breadcrumb-item active">Technicians</li>
                     </ol>
                  </div>
               </div>
               <div class="d-flex flex-column flex-md-row justify-content-between align-items-center mb-3">
                  <a href="{% url 'tecnicos:add_tecnicos' %}"><button type="button" class="btn btn-success mb-3 mb-md-0 waves-effect waves-light" onclick="addNewPart()">Add new</button></a>
                  <div class="col-md-6 mb-3 d-flex align-items-center justify-content-end">
                        <div class="span-container d-flex">
                           <input type="date" name="fromdate" class="form-control" data-date-inline-picker="true">
                           <input type="date" name="todate" class="form-control" data-date-inline-picker="true">
                           <input type="submit" value="Search" class="btn btn-secondary">
                           <!--                                                <input type="text" name="daterange" value="12/01/2021 - 12/31/2021" class="form-control" id="id_date_range"/>-->
                        </div>
                        <!--                                                <input type="text" name="daterange" value="12/01/2021 - 12/31/2021" class="form-control" id="id_date_range"/>-->
                     </div>
               </div>
            </div>
            <!-- end page title -->
            <div class="row">
               <div class="col-12">
                  <div>
                     <div>
                        <div class="table-responsive mb-4">
                           {% if tecnicos %}
                           <br>
                           <table class="table table-centered datatable dt-responsive nowrap table-card-list display" style="border-collapse: collapse; border-spacing: 0 12px; width: 100%;" id="datatable">
                              <thead>
                                 <tr class="bg-transparent">
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Phone number</th>
                                    <th>Notes</th>
                                    <th style="width: 120px;">Action</th>
                                    <th style="width: 120px;"></th>
                                    <th style="width: 120px;"></th>
                                 </tr>
                              </thead>
                              <tbody>
                                 {% for tecnico in tecnicos %}
                                 <tr>
                                    <td>{{tecnico.id}}</td>
                                    <td>{{tecnico.nombreTecnico}}</td>
                                    <td><a href="mailto:name1@domain.com">{{tecnico.emailTecnico}}</a></td>
                                    <td>{{tecnico.telTecnico}}</td>
                                    <td>{{tecnico.notasTecnico}}</td>
                                    <td><a href="{% url 'tecnicos:tecnicos_detail' tecnico.id%}">Detail</a></td>
                                    <td><a href="{% url 'tecnicos:edit_tecnicos' tecnico.id%}">Edit</a></td>
                                    <td><a href="{% url 'tecnicos:eliminar_tecnicos' tecnico.id%}" class="text-danger" >Delete</a></td>
                                 </tr>
                                 {% endfor %}
                              </tbody>
                           </table>
                           {% endif %}
                        </div>
                     </div>
                  </div>
                  <!-- end col -->
               </div>
               <!-- end row -->
            </div>
            <!-- container-fluid -->
         </div>
   </form>
   <!-- End Page-content -->
   <footer class="footer">
   <div class="container-fluid">
   <div class="row">
   <div class="col-sm-6">
   <script>document.write(new Date().getFullYear())</script> © The Shop.
   </div>
   <div class="col-sm-6">
   <div class="text-sm-end d-none d-sm-block">
   </div>
   </div>
   </div>
   </div>
   </footer>
   <!-- The Modal -->
   <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog modal-dialog-centered modal-xl">
   <div class="modal-content">
   <div class="modal-header">
   <!-- <h5 class="modal-title" id="exampleModalLabel"></h5> -->
   <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
   </div>
   <div class="modal-body">
   <div class="table-responsive">
   <div class="row">
   <div class="col-lg-12">
   <!-- Swiper -->
   <div class="swiper mySwiper">
   <div class="swiper-wrapper">
   <div class="swiper-slide"><img src="images/square-logo-demo.jpg" alt="LOGO" height="68"></div>
   <div class="swiper-slide"><img src="images/square-logo-demo.jpg" alt="LOGO" height="68"></div>
   <div class="swiper-slide"><img src="images/square-logo-demo.jpg" alt="LOGO" height="68"></div>
   <div class="swiper-slide"><img src="images/square-logo-demo.jpg" alt="LOGO" height="68"></div>
   <div class="swiper-slide"><img src="images/square-logo-demo.jpg" alt="LOGO" height="68"></div>
   <div class="swiper-slide"><img src="images/square-logo-demo.jpg" alt="LOGO" height="68"></div>
   <div class="swiper-slide"><img src="images/square-logo-demo.jpg" alt="LOGO" height="68"></div>
   <div class="swiper-slide"><img src="images/square-logo-demo.jpg" alt="LOGO" height="68"></div>
   <div class="swiper-slide"><img src="images/square-logo-demo.jpg" alt="LOGO" height="68"></div>
   </div>
   <div class="swiper-pagination"></div>
   </div>
   </div>
   </div>
   <!-- end row -->
   </div>
   </div>
   <div class="modal-footer">
   <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
   </div>
   </div>
   </div>
   </div>
   </div>
   <!-- end main content-->
</div>
<!-- END layout-wrapper -->
{% endblock %}

SistemaCarros/tecnicos/templates/tecnicos/tecnicos-detail.html
{% extends 'SistemaCarros/base.html' %}
{% load widget_tweaks %}



{% block content %}


            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">

                <div class="page-content">
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box d-flex align-items-center justify-content-between">
                                    <h4 class="mb-0">Technicians</h4>

                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="{% url 'dashboard:dashboard' %}">The Shop</a></li>
                                            <li class="breadcrumb-item active">Technicians</li>
                                        </ol>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <!-- end page title -->


                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">

                                                            <h4>{{ tecnico.nombreTecnico }} {{ tecnico.apellidoTecnico }}</h4>
                                                            <hr>
                                                            <p><b>Email: </b>{{ tecnico.emailTecnico }}</p>
                                                            <p><b>Phone Number: </b>{{ tecnico.telTecnico }}</p>
                                                            <p><b>Phone Number2: </b>{{ tecnico.telTecnico2 }}</p>
                                                            <p><b>Notes: </b>{{ tecnico.notasTecnico }}</p>


                                </div>
                            </div> <!-- end col -->
                        </div> <!-- end row -->



                    </div> <!-- container-fluid -->
                </div>
                <!-- End Page-content -->
            </div>

{% endblock %}

SistemaCarros/tecnicos/templates/tecnicos/tecnicos_confirm_delete.html
{% extends 'SistemaCarros/base.html' %}
{% block content %}


            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">

                <div class="page-content">
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box d-flex align-items-center justify-content-between">
                                    <h4 class="mb-0">Technicians</h4>

                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="{% url 'dashboard:dashboard' %}">The Shop</a></li>
                                            <li class="breadcrumb-item active">Technicians</li>
                                        </ol>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <!-- end page title -->


                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">



                                        <form method="post">{% csrf_token %}
                                            <p>Are you sure you want to delete "{{ tecnico.nombreTecnico }}"?</p>
                                            <button class="btn btn-danger mb-3" type="submit">Delete</button>
                                        </form>



                                    </div>
                                </div>
                            </div> <!-- end col -->
                        </div> <!-- end row -->



                    </div> <!-- container-fluid -->
                </div>
                <!-- End Page-content -->
            </div>




{% endblock %}