SistemaCarros/Foto/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


app_name='Foto'

urlpatterns=[
    path('add',views.create_Foto,name='foto')
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SistemaCarros/Presupuestos/urls.py
from . import views
from django.urls import path

app_name='Presupuestos'

urlpatterns=[
    # path('new-customer',views.create_Presupuestos,name='nuevo-presupuestos'),
    path('step1',views.step1,name='step1'),
    path('step2',views.step2,name='step2'),
    path('step3',views.step3,name='step3'),
    path('step4',views.step4,name='step4'),
    path('step5',views.step5,name='step5'),
    path('step6',views.step6,name='step6'),
    path('step7/',views.step7,name='step7'),
    path('step8',views.step8,name='step8'),
    path('',views.presupuestosIndex,name='presupuestos'),
    path('add-pay/<int:pk>',views.addPay,name='add-pay'),
    path('add-part/<int:pk>',views.addPart,name='add-part'),
    path('add-labor/<int:pk>',views.addLabor,name='add-labor'),
    path('detail/<int:pk>', views.detail_presupuestos, name='detail'),
    path('cancel/<int:pk>', views.cancel_presupuestos, name='cancel-estimate'),
    path('download-pdf/<int:pk>', views.download_pdf, name='download-estimate'),
    path('detail-in-pdf/<int:pk>', views.detail_in_pdf, name='detail-in-pdf'),
]

SistemaCarros/ReporteGanancias/urls.py
from . import views
from django.urls import path,register_converter


app_name='ReporteGanancias'

class FloatUrlParameterConverter:
    regex = '[0-9]+\.?[0-9]+'

    def to_python(self, value):
        return float(value)

    def to_url(self, value):
        return str(value)
register_converter(FloatUrlParameterConverter, 'float')

urlpatterns=[
    path('',views.IndexReporteGanancias.as_view(),name='reporteganancias'),
    path('reports-debtors', views.reportsDebtors, name='debtors'),
    path('reports-pending-stock', views.pendingStock.as_view(), name='pending-stock'),
    path('reports-records', views.Records.as_view(), name='records'),
    path('reports-technicians', views.Technicians, name='technicians'),
    path('reports-workshops', views.Workshops, name='workshops'),
    path('reports-technicians-add-payment/<int:estimate>/<int:technico>', views.techniciansAddPayment, name='techniciansAddPayment'),
    path('reports-technicians-view-payment/<int:estimate>/<int:technico>/<float:percent>/<float:total>', views.techniciansViewPayment, name='techniciansViewPayment'),
    path('send-email/<int:pk>', views.send_email, name='send-email'),
    path('add-pay/<int:pk>',views.addPay,name='add-pay'),
    path('add-part/<int:pk>',views.addPart,name='add-part'),
    path('add-labor/<int:pk>',views.addLabor,name='add-labor'),
    path('detail-invoice/<int:pk>',views.ViewInvoice,name='detail-invoice'),
    path('reports-technicians-delete-payment/<int:id>', views.DeletePayment, name='technicianDeletePayment')
    # path('edit/<int:pk>', views.edit_inventory.as_view(), name='edit_tecnicos'),
    # path('edit',views.addPart.as_view(),name='add-part'),
] 

SistemaCarros/SistemaCarros/urls.py
from django.contrib import admin
from django.urls import path, include
from Usuarios import views as user_views
from Usuarios.views import PasswordsChangeView, EditProfilePageView
from . import views as sistema_views, views
from django.contrib.auth import views as authentication_views, logout
from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('carros/',include('carros.urls')),
    path('cliente-empresas/',include('ClienteEmpresas.urls')),
    path('clientes/', include('Clientes.urls')),
    #path('presupuestos/', include('Presupuestos.urls')),
    path('estimates/', include('Presupuestos.urls')),
    path('mano-obra/', include('ManoObra.urls')),
    path('parte/', include('Parte.urls')),
    path('informacion-tiendas/', include('InformacionTiendas.urls')),
    path('pagos/', include('Pagos.urls')),
    path('reports/', include('ReporteGanancias.urls')),
    path('foto/', include('Foto.urls')),
    path('detalle/', include('Detalle.urls')),
    path('invoices/', include('invoices.urls')),
    path('technicians/', include('tecnicos.urls')),
    # path('inventory/', include('inventory.urls')),
    #Dashboard
    #path('nuevo_cliente',user_views.nuevo_cliente, name='nuevo_cliente'),


    #Authentications
    path('registro/',user_views.registro,name='registro'),
    path('login/',authentication_views.LoginView.as_view(template_name='Usuarios/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='Usuarios/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
    path('profile/change-password/',PasswordsChangeView.as_view(template_name='Usuarios/change-password.html'),name='change-password'),
    path('password_success',user_views.password_success,name="password_success"),
    path('profile/<int:pk>/edit-profile/',EditProfilePageView.as_view(),name='edit-profile'),

    #RichFields
    path('djrichtextfield/', include('djrichtextfield.urls')),

    #search
    path('search/',sistema_views.search, name='search'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        ) 

SistemaCarros/ReporteGanancias/models.py
from django.db import models

# Create your models here.
from Clientes.models import Clientes
from Foto.models import Foto
from django.db import models

# Create your models here.
from Clientes.models import Clientes
from Foto.models import Foto
from ManoObra.models import ManoObra
from Pagos.models import Pagos
from Parte.models import Parte
from carros.models import Carro
from inventory.models import Inventory
from Presupuestos.models import Presupuestos
from tecnicos.models import Tecnicos
class ReporteGanancias(models.Model):

    cliente= models.ForeignKey(Clientes, on_delete=models.CASCADE)
    carro=models.ForeignKey(Carro, on_delete=models.CASCADE)
    mano_obra=models.ForeignKey(ManoObra, on_delete=models.CASCADE)
    parteInventory=models.ForeignKey(Inventory, on_delete=models.CASCADE)
    garantia=models.CharField(max_length=255,default=0)
    pago = models.ForeignKey(Pagos, on_delete=models.CASCADE)
    foto = models.ForeignKey(Foto, on_delete=models.CASCADE)


    def __str__(self):
        #return f'{self.cliente} {self.presupuesto} {self.mano_obra} {self.parte} {self.subcontratar_trabajos} {self.otros_costos} {self.descuento}'
        return f'{self.cliente} {self.carro}{self.mano_obra} {self.parte}{self.garantia}{self.pago}{self.foto}'


class ReporteTechnician(models.Model):
    estimate = models.ForeignKey(Presupuestos, on_delete=models.CASCADE)
    technician = models.ForeignKey(Tecnicos, on_delete=models.CASCADE)
    content = models.CharField(max_length=255, blank=False)
    quantity = models.FloatField(default=0, null=False)
    register_time=models.DateTimeField(auto_now=True)

SistemaCarros/ReporteGanancias/forms.py
from django import forms
from .models import ReporteTechnician

class ReporteTechnicianForm(forms.ModelForm):
    class Meta:
        model = ReporteTechnician
        fields = ["content", "quantity"]
        widgets={
            'content': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'quantity': forms.NumberInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }

SistemaCarros/ReporteGanancias/views.py
from django.core.mail import send_mail
from django.forms import formset_factory
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.template import loader
from django.views.generic import TemplateView, ListView
import json
# from inventory.models import Inventory
from ManoObra.models import ManoObra
from Presupuestos.forms import PresupuestosPagosForm, PresupuestosParteForm, PresupuestosForm, PresupuestosManoObraForm
from Presupuestos.models import Presupuestos
from carros.models import Carro
from invoices.models import Invoices
from tecnicos.models import Tecnicos
from .forms import ReporteTechnicianForm
from django.db.models import Count, Sum
from django.contrib import  messages
# Create your views here.
from .models import ReporteGanancias, ReporteTechnician
from .models import Parte
from datetime import datetime

class IndexReporteGanancias(TemplateView):
    template_name='ReporteGanancias/list.html'



def reportsDebtors(request):
    if request.method =='POST':
        fromdate=request.POST['fromdate'] + " 00:00:00"
        todate=request.POST['todate'] + " 23:59:59"
        presupuestos_all=Presupuestos.objects.filter(register_time__range=(fromdate,todate), status="PENDING")
    else:
        presupuestos_all = Presupuestos.objects.filter(status="PENDING")
        fromdate = datetime.now().date().strftime("%Y-%m-%d")
        todate = datetime.now().date().strftime("%Y-%m-%d")
    return render(request, "ReporteGanancias/reports-debtors.html",
                  {'presupuestos': presupuestos_all, 'fromdate':fromdate, 'todate':todate})

def send_email(request,pk):
    presupuesto = Presupuestos.objects.get(pk=pk)
    html_message = loader.render_to_string(
        'Presupuestos/estimate-pdf.html',
        {'presupuesto': presupuesto}
    )
    email_subject = 'Your Estimate!'
    to_list = presupuesto.presupuesto.cliente.correo
    send_mail(email_subject, 'message', None, [to_list], fail_silently=False, html_message=html_message)
    messages.success(request, "Updated Estimate is sent by Email")
    return redirect('ReporteGanancias:debtors')
def addPay(request, pk):
    extra_forms = 1
    ParteFormSet = formset_factory(PresupuestosPagosForm, extra=extra_forms, max_num=20, can_delete=True)
    if request.method == 'POST':
        formset = ParteFormSet(request.POST, request.FILES, prefix='form')
        presupuesto = Presupuestos.objects.get(pk=pk)
        if formset.is_valid():
            for form in formset:
                if not form.cleaned_data["DELETE"]:
                    model_instance = form.save(commit=False)
                    model_instance.estimate = Presupuestos.objects.get(pk=pk)
                    presupuesto.total_paid += round(model_instance.cantidad_pagada,2 )
                    model_instance.save()
            presupuesto.save()
        check_Invoice(pk)
        messages.success(request, "Payment is Added")
        return redirect('ReporteGanancias:debtors')
    else:
        formset = ParteFormSet()
    return render(request, 'Presupuestos/estimate-add-payment.html', {
        'formset': formset,
    })



def addPart(request, pk):
    extra_forms = 1
    ParteFormSet = formset_factory(PresupuestosParteForm, extra=extra_forms, max_num=20, can_delete=True)
    presupuestos = Presupuestos.objects.filter(id=pk).values()[0]
    presupuestosForm = PresupuestosForm(initial=presupuestos)
    if request.method == 'POST':
        formset = ParteFormSet(request.POST, request.FILES, prefix='form')
        if formset.is_valid():
            for form in formset:
                if not form.cleaned_data["DELETE"]:
                    model_instance = form.save(commit=False)
                    model_instance.estimate_id = Presupuestos.objects.get(pk=pk)
                    model_instance.save()

            presupuestos = Presupuestos.objects.get(pk=pk)

            if (request.POST['descuento_parte'] == "Quantity"):
                presupuestos.descuentoTotal_parte += float(request.POST['descuentoTotal_parte'])
            elif(request.POST['descuento_parte'] == "Percentage"):
                if not float(request.POST['descuentoTotal_parte']) == 0:
                    presupuestos.descuentoTotal_parte += (100 - float(request.POST['descuentoTotal_parte'])) * float(request.POST['total_parte']) / float(request.POST['descuentoTotal_parte'])
            print(float(request.POST['total_parte']))
            presupuestos.total_parte += float(request.POST['total_parte'])
            presupuestos.descuentoTotal_parte = round(presupuestos.descuentoTotal_parte, 2)

            presupuestos.save()
            messages.success(request, "part is Added")
        return redirect('ReporteGanancias:debtors')
    else:
        formset = ParteFormSet()

    return render(request, 'Presupuestos/estimate-add-parts.html', {
        'presupuestosForm': presupuestosForm,
        'formset': formset,
    })



def addLabor(request, pk):
    extra_forms = 1
    ManoObraFormSet = formset_factory(PresupuestosManoObraForm, extra=extra_forms, max_num=20, can_delete=True)
    if request.method == 'POST':
        formset = ManoObraFormSet(request.POST, request.FILES, prefix='form')

        if formset.is_valid():
            for form in formset:
                if not form.cleaned_data["DELETE"]:
                    model_instance = form.save(commit=False)
                    model_instance.estimate_ids = Presupuestos.objects.get(pk=pk)
                    model_instance.save()
            presupuestos = Presupuestos.objects.get(pk=pk)

            if (request.POST['descuento_manaobra'] == "Quantity"):
                presupuestos.descuentoTotal_manaobra += float(request.POST['descuentoTotal_manaobra'])
            elif(request.POST['descuento_manaobra'] == "Percentage"):
                if not float(request.POST['descuentoTotal_manaobra']) == 0:
                    presupuestos.descuentoTotal_manaobra += (100 - float(request.POST['descuentoTotal_manaobra'])) * float(request.POST['total_manaobra'])/float(request.POST['descuentoTotal_manaobra'])
            presupuestos.total_manaobra += float(request.POST['total_manaobra'])
            presupuestos.descuentoTotal_manaobra = round(presupuestos.descuentoTotal_manaobra, 2)
            presupuestos.save()
            messages.success(request, "Labour is Added")
        return redirect('ReporteGanancias:debtors')
    else:
        formset = ManoObraFormSet()
    return render(request, 'Presupuestos/estimate-add-labor.html', {
        'formset': formset,
    })


def pendingStock(request):

    if request.method == 'POST':
        fromdate=request.POST.get('fromdate')
        todate = request.POST.get('todate')
        searchresult = Parte.objects.filter(fecha_registro__range=(fromdate, todate))
        queryset = Parte.objects.filter(quantity__lt=10)
        return render(request,'ReporteGanancias/reports-pending-stock.html',{'parte':searchresult,'queryset':queryset})

    else:
        displaydata = Parte.objects.all()
    return render(request, 'ReporteGanancias/reports-pending-stock.html', {'parte': displaydata,'queryset':queryset})


class pendingStock(ListView):
    model=Parte
    template_name = 'ReporteGanancias/reports-pending-stock.html'
    context_object_name='parte'
    queryset = Parte.objects.filter(quantity__lt=10)


class Records(TemplateView):

    template_name = 'ReporteGanancias/reports-records.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        invoices = []
        carros_list = Invoices.objects.values('estimate__carro__id').distinct()
        for carros in carros_list:
            for invoice in Invoices.objects.filter(estimate__carro__id = carros['estimate__carro__id']):
                invoices.append(invoice)
        context['invoices'] = invoices
        return context
def ViewInvoice(request,pk):
    invoice=Invoices.objects.get(pk=pk)
    presupuesto =  Presupuestos.objects.get(pk=invoice.estimate_id)
    return render(request,'ReporteGanancias/reports-invoice-detail.html',{'invoice':invoice,'presupuesto':presupuesto})
def Technicians(request):

    if request.method=="POST":
        fromdate = request.POST['fromdate'] + " 00:00:00"
        todate = request.POST['todate'] + " 23:59:59"
        estimates = Presupuestos.objects.filter(register_time__range=(fromdate, todate))
    else:
        estimates = Presupuestos.objects.all()
        fromdate = datetime.now().date().strftime("%Y-%m-%d") + " 00:00:00"
        todate = datetime.now().date().strftime("%Y-%m-%d") + " 00:00:00"
    tech_estimates = []
    count = 0
    for estimate in estimates:
        technicians_ids = []
        technicians = []
        for labour in estimate.manoobra_set.values():
            id = ManoObra.objects.get(pk=labour['id']).tecnico.id
            if not id in technicians_ids:
                technicians_ids.append(id)
        for tech_id in technicians_ids:
            technicians_mano = []
            sum = 0
            for labour in estimate.manoobra_set.filter(tecnico__id=tech_id).values():
                technicians_mano.append(ManoObra.objects.get(pk=labour['id']))
                sum += labour["tarifa_total"]
            technicians.append({'labour':technicians_mano, 'sum':sum, 'count':count})

        tech_estimates.append({
            "presupuesto": estimate,
            "labours": technicians,
            'labour_count':count,
        })
        count += len(technicians)

    return render(request, "ReporteGanancias/reports-technicians.html", {"estimates":tech_estimates, "fromdate":fromdate, "todate":todate})
    # queryset=Presupuestos.objects.all()


def Workshops(request):
    template_name = 'ReporteGanancias/reports-workshops.html'

    if request.method =='POST':
        fromdate=request.POST['fromdate'] + " 00:00:00"
        todate=request.POST['todate'] + " 23:59:59"

SistemaCarros/ReporteGanancias/templates/ReporteGanancias/reports-debtors.html
{% extends 'SistemaCarros/base.html' %}
{% load widget_tweaks %}
{% load mathfilters %}

{% block content %}




            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">

                <div class="page-content">
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12 mb-3">
                                <div class="page-title-box d-flex align-items-center justify-content-between">
                                    <h4 class="mb-0">Debtors report</h4>

                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                                            <li class="breadcrumb-item"><a href="reports.html">Reports</a></li>
                                            <li class="breadcrumb-item active">Debtors</li>
                                        </ol>
                                    </div>

                                </div>
                            </div>

                            <div class="d-flex flex-column flex-md-row justify-content-end align-items-center mb-3">



                                <div class="d-flex justify-content-end align-items-center col-12 col-md-4">
                                    <div class="text-right">
                                        <label class="m-0">Date range:&nbsp;&nbsp;</label>
                                    </div>
                                    <div class="d-flex align-items-center">
                                        <form method="post">
                                        <div class="span-container d-flex">

                                                {% csrf_token %}
                                                <input type="date" value={{ fromdate }} name="fromdate" class="form-control" data-date-inline-picker="true">
                                                <input type="date" value={{ todate }} name="todate" class="form-control" data-date-inline-picker="true">
                                                <input type="submit" value="Search" class="btn btn-secondary">


                           <!--                                                <input type="text" name="daterange" value="12/01/2021 - 12/31/2021" class="form-control" id="id_date_range"/>-->
                                        </div>
                                        </form>
                                    </div>
                                </div>

                            </div>


                        </div>
                        <!-- end page title -->


                        <div class="row mt-3">
                            <div class="col-lg-12">

                                <div class="table-responsive mb-4">
                                    <table class="table table-centered datatable dt-responsive nowrap table-card-list" style="border-collapse: collapse; border-spacing: 0 12px; width: 100%;">
                                        <thead>
                                            <tr class="bg-transparent">

                                                <th>Estimate ID</th>
                                                <th>Date</th>
                                                <th>Billing Name</th>
                                                <th>Pending</th>
                                                <th>Total</th>
                                                <th>Status</th>
                                                <th>Download PDF</th>
                                                <th>Add parts</th>
                                                <th>Add labor</th>
                                                <th>Add payment</th>
                                                <th style="width: 120px;">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            {% for presupuesto in presupuestos %}
                                            <tr>
                                                <td>
                                                    <div class="form-check text-center font-size-16">
                                                        <input type="checkbox" class="form-check-input" id="invoicecheck1">
                                                        <label class="form-check-label" for="invoicecheck1"></label>
                                                        <a href="javascript: void(0);" class="text-dark fw-bold">#MN{{ presupuesto.id  }}</a>

                                                    </div>
                                                </td>
                                                <td>
                                                    {{presupuesto.register_time.date}}
                                                </td>
                                                <td>
                                                    {{presupuesto.cliente.nombre}}
                                                </td>
                                                <td>
                                                    ${{presupuesto.total_parte|addition:presupuesto.total_manaobra|sub:presupuesto.total_paid|floatformat:2}}
                                                </td>

                                                <td>
                                                    ${{ presupuesto.total_parte|addition:presupuesto.total_manaobra|floatformat:2 }}
                                                </td>

                                                <td>
                                                    {% if presupuesto.status == "PENDING" %}
                                                        <span class="badge bg-soft-warning font-size-12">Pending</span>
                                                    {% elif presupuesto.status == "CANCELED" %}
                                                        <span class="badge bg-soft-danger font-size-12">Canceled</span>
                                                    {% else %}
                                                        <span class="badge bg-soft-success font-size-12">Paid</span>
                                                    {% endif %}
                                                </td>

                                                <td>
                                                    <div>
                                                        <a href="{% url 'Presupuestos:download-estimate' presupuesto.id %}" class="btn btn-light btn-sm w-xs">PDF <i class="uil uil-download-alt ms-2"></i></a>
                                                    </div>
                                                </td>

                                                <td>
                                                    <a href="{% url 'ReporteGanancias:add-part' presupuesto.id %}" class="px-3 text-success"><i class="uil uil-plus-circle font-size-18"></i></a>
                                                </td>
                                                <td>
                                                    <a href="{% url 'ReporteGanancias:add-labor' presupuesto.id %}" class="px-3 text-success"><i class="uil uil-plus-circle font-size-18"></i></a>
                                                </td>
                                                <td>
                                                    <a href="{% url 'ReporteGanancias:add-pay' presupuesto.id %}" class="px-3 text-success"><i class="uil uil-plus-circle font-size-18"></i></a>
                                                </td>

                                                <td>
                                                    <a href="{% url 'Presupuestos:detail' presupuesto.id %}"><i class="uil uil-search font-size-18"></i></a>

                                                    <a href="{% url 'ReporteGanancias:send-email' presupuesto.id %}"><i class="uil uil-mailbox-alt font-size-18"></i></a>
                                                </td>
                                            </tr>
                                        {% endfor%}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <!-- end row -->



                    </div> <!-- container-fluid -->
                </div>
                <!-- End Page-content -->


                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-6">
                                <script>document.write(new Date().getFullYear())</script> © Mechanix Boss POS
                            </div>
                            <div class="col-sm-6">
                                <div class="text-sm-end d-none d-sm-block">

                                </div>
                            </div>
                        </div>
                    </div>
                </footer>

            </div>
            <!-- end main content-->

{% endblock %}

SistemaCarros/ReporteGanancias/templates/ReporteGanancias/reports-technicians-add-payment.html
{% extends 'SistemaCarros/base.html' %}
{% load widget_tweaks %}
{% block content %}
            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">

                <div class="page-content">
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12 mb-3">
                                <div class="page-title-box d-flex align-items-center justify-content-between">
                                    <h4 class="mb-0">Adding payment...</h4>

                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="dashboard.html">Dashboard</a></li>
                                            <li class="breadcrumb-item"><a href="reports.html">Reports</a></li>
                                            <li class="breadcrumb-item"><a href="reports-technicians.html">Technicians payments</a></li>
                                            <li class="breadcrumb-item active">Adding payments</li>
                                        </ol>
                                    </div>

                                </div>
                            </div>



                        </div>
                        <!-- end page title -->


                        <form enctype="multipart/form-data" method="post">
                            {% csrf_token %}
                            <div class="row mt-3">
                            <div class="col-md-4">
                                <div class="row mt-3">
                                    <div class="col-12">
                                        <div class="card">
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="mb-3">
                                                            <label class="form-label" for="validationCustom08">Concept</label>
                                                            {{ technicianForm.content}}
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <div class="mb-3">
                                                            <label class="form-label" for="validationCustom08">Quantity</label>
{#                                                            <input type="text" class="form-control" id="validationCustom08" placeholder="" required="">#}
                                                            {{ technicianForm.quantity}}
                                                        </div>
                                                    </div>
                                                </div>
                                                <input type="submit" class="btn btn-block btn-success mb-4" value="+ Add pay">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>



                        </div> <!-- end row -->
                        </form>


                    </div> <!-- container-fluid -->
                </div>
                <!-- End Page-content -->
{% endblock %}