SistemaCarros/Foto/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


app_name='Foto'

urlpatterns=[
    path('add',views.create_Foto,name='foto')
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SistemaCarros/SistemaCarros/urls.py
from django.contrib import admin
from django.urls import path, include
from Usuarios import views as user_views
from Usuarios.views import PasswordsChangeView, EditProfilePageView
from . import views as sistema_views, views
from django.contrib.auth import views as authentication_views, logout
from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('carros/',include('carros.urls')),
    path('cliente-empresas/',include('ClienteEmpresas.urls')),
    path('clientes/', include('Clientes.urls')),
    #path('presupuestos/', include('Presupuestos.urls')),
    path('estimates/', include('Presupuestos.urls')),
    path('mano-obra/', include('ManoObra.urls')),
    path('parte/', include('Parte.urls')),
    path('informacion-tiendas/', include('InformacionTiendas.urls')),
    path('pagos/', include('Pagos.urls')),
    path('reports/', include('ReporteGanancias.urls')),
    path('foto/', include('Foto.urls')),
    path('detalle/', include('Detalle.urls')),
    path('invoices/', include('invoices.urls')),
    path('technicians/', include('tecnicos.urls')),
    # path('inventory/', include('inventory.urls')),
    #Dashboard
    #path('nuevo_cliente',user_views.nuevo_cliente, name='nuevo_cliente'),


    #Authentications
    path('registro/',user_views.registro,name='registro'),
    path('login/',authentication_views.LoginView.as_view(template_name='Usuarios/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='Usuarios/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
    path('profile/change-password/',PasswordsChangeView.as_view(template_name='Usuarios/change-password.html'),name='change-password'),
    path('password_success',user_views.password_success,name="password_success"),
    path('profile/<int:pk>/edit-profile/',EditProfilePageView.as_view(),name='edit-profile'),

    #RichFields
    path('djrichtextfield/', include('djrichtextfield.urls')),

    #search
    path('search/',sistema_views.search, name='search'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        ) 

SistemaCarros/carros/urls.py
from . import views
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from SistemaCarros import settings

# from django.conf import settings
from django.conf.urls.static import static


app_name='carros'

urlpatterns=[
    #/carros/
    path('',views.list_cars,name='list_cars'),
    path('add',views.create_carros.as_view(), name='create_carros'),
    path('addpicture',views.create_carros_picture, name='create_carros_picture'),
    path('addwarranty',views.create_carros_warranty, name='create_carros_warranty'),
    path('edit/<int:pk>',views.EditClassView.as_view(), name='edit_carros'),
    path('image_detail',views.Imagedetail, name='image_detail'),
    path('<int:pk>/',views.detail_carro.as_view(),name='detail_carro'),
    path('delete/<int:pk>',views.delete_carro.as_view(), name='eliminar_carros'),
    path('detail_invoice/<int:pk>', views.detail_invoices, name='detail_invoice'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        ) 

SistemaCarros/dashboard/urls.py
from . import views
from django.urls import path

app_name='dashboard'

urlpatterns=[
    #/dashboard/
    path('',views.dashboard,name='dashboard'),

]

SistemaCarros/carros/models.py
from datetime import timezone, datetime
from django.db import models

# Create your models here.
from Clientes.models import Clientes
import json

class Carro(models.Model):
    placas=models.CharField(max_length=255, blank=True)
    tipo=models.CharField(max_length=255, blank=True)
    marca=models.CharField(max_length=255, blank=True)
    modelo=models.CharField(max_length=255, blank=True)
    año=models.IntegerField()
    vin=models.CharField(max_length=255, blank=True)
    color=models.CharField(max_length=255, blank=True)
    motor=models.CharField(max_length=255, blank=True)
    agente_seguros=models.CharField(max_length=255, blank=True)
    compañia_seguros=models.CharField(max_length=255, blank=True)
    no_politica=models.CharField(max_length=255,blank=True)
    cliente= models.ForeignKey(Clientes, on_delete=models.SET_NULL, null=True,blank=True)
    fotosCarro=models.TextField(null=True,blank=True)
    garantia=models.TextField(null=True,blank=True)
    fecha_registros = models.DateTimeField(default=datetime.now, null=True,blank=True)

#customize model property for main view of fotosCarro
    @property
    def new_name(self):
        if self.fotosCarro == '':
            return None
        temp=json.loads(self.fotosCarro)
        if len(temp) == 0:
            return None
        tempkey=sorted(temp.keys())
        for item in reversed(tempkey):
            if temp[item][1]=="on":
                return item;
        return list(json.loads(self.fotosCarro).keys())[0]

    @property
    def garantia_name(self):
        if self.garantia == '':
            return None
        temp=json.loads(self.garantia)
        if len(temp) == 0:
            return None
        tempkey=sorted(temp.keys())
        for item in reversed(tempkey):
            if temp[item][1]=="on":
                return item;
        return list(json.loads(self.garantia).keys())[0]
    def orig_name(self):
        return list(json.loads(self.fotosCarro).values())[0]
    def __str__(self):
        return f'{self.placas} {self.año}{self.marca} {self.modelo} {self.tipo}{self.motor}{self.vin}{self.color}' \
               f'{self.agente_seguros}{self.compañia_seguros}{self.no_politica}{self.cliente}{self.fotosCarro}{self.garantia}' \
               f'{self.fecha_registros}'

SistemaCarros/carros/forms.py
from django import forms
from .models import Carro


class CarroForm(forms.ModelForm):
    class Meta:
        model=Carro
        fields = ['placas','año','modelo','marca','tipo','motor','vin','color',
                  'agente_seguros','compañia_seguros','no_politica','cliente','fotosCarro','garantia']
        exclude = ['fecha_registros']
        widgets = {
            'placas': forms.TextInput(
                attrs={

                    'class': 'form-control',

                }
            ),
            'año': forms.TextInput(
                attrs={

                    'class': 'form-control'
                }
            ),
            'marca': forms.TextInput(
                attrs={

                    'class': 'form-control'
                }
            ),
            'modelo': forms.TextInput(
                attrs={

                    'class': 'form-control'
                }
            ),
            'tipo': forms.TextInput(
                attrs={

                    'class': 'form-control'
                }
            ),

            'vin': forms.TextInput(
                attrs={

                    'class': 'form-control'
                }
            ),
            'color': forms.TextInput(
                attrs={

                    'class': 'form-control'
                }
            ),
            'motor': forms.TextInput(
                attrs={

                    'class': 'form-control'
                }
            ),
            'agente_seguros': forms.TextInput(
                attrs={

                    'class': 'form-control'
                }
            ),
            'compañia_seguros': forms.TextInput(
                attrs={

                    'class': 'form-control'
                }
            ),
            'no_politica': forms.TextInput(
                attrs={

                    'class': 'form-control'
                }
            ),
            'cliente': forms.Select(
                attrs={
                    'class': 'form-select'
                }
            ),
            'fotosCarro':forms.Textarea(
                attrs={
                    'class': 'form-control',
                    # 'multiple': True,
                    'id': 'file-input',
                    'onchange':'preview()',
                }
            ),
            'garantia':forms.Textarea(
                attrs={
                    'class': 'form-control',
                    # 'multiple': True,
                    'id': 'file-inputz',
                    'onchange': 'preview()',
                    # 'id':'pro-images',
                    # 'click': "$('#pro-images').click()",
                }
            ),
            'fecha_registros': forms.DateInput(
                attrs={
                    'class': 'form-control',
                }
            ),

        }


class DateRangeForm(forms.Form):
    start_date = forms.DateField()
    end_date = forms.DateField() 

SistemaCarros/carros/views.py
import json
import os

from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, UpdateView, CreateView, DeleteView, DetailView
from django.views.generic.list import ListView

from django.shortcuts import render, redirect

# Create your views here.
from Presupuestos.models import Presupuestos
from SistemaCarros import settings
from carros.forms import CarroForm
from carros.models import Carro
from django.core.files.storage import default_storage, FileSystemStorage

from invoices.models import Invoices


class IndexClassView(ListView):
    model=Carro
    template_name = 'carros/index.html'
    context_object_name='carros'
    queryset=Carro.objects.all()


def list_cars(request):

    if request.method == 'POST':
        fromdate = request.POST.get('fromdate')
        todate = request.POST.get('todate')
        searchresult = Carro.objects.filter(fecha_registros__range=(fromdate, todate))
        return render(request,'carros/index.html',{'carros':searchresult})

    else:
        displaydata = Carro.objects.all()
    return render(request, 'carros/index.html', {'carros': displaydata})

def Imagedetail(request):
    car_id = request.POST.get('id')
    current_car = Carro.objects.get(id=car_id)
    return JsonResponse(json.dumps(list(json.loads(current_car.fotosCarro).keys())), safe=False)


class detail_carro(DetailView):
    template_name = 'carros/carros-detail.html'
    queryset=Carro.objects.all()
    context_object_name = 'carros'



class EditClassView(SuccessMessageMixin,UpdateView):
    model = Carro
    form_class=CarroForm
    template_name = 'carros/edit.html'
    success_url = reverse_lazy('carros:list_cars')
    success_message = "%(modelo)s this was updated successfully"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(UpdateView, self).get(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if len(list(Presupuestos.objects.filter(carro_id=self.kwargs.get("pk"))))==0:
            context['invoices']=[]
            return context
        presupuestos_per_car = Presupuestos.objects.values_list('id').filter(carro_id=self.kwargs.get("pk"))
        car_range=[]
        for temp in presupuestos_per_car:
            car_range.append(temp[0])
        invoices_per_car=[]
        # for presupuesto in presupuestos_per_car:
        #     invoices_per_car.append(Invoices.objects.filter(estimate_id=presupuesto.id).first())
        context['invoices'] = Invoices.objects.filter(estimate_id__in=car_range)

        return context
#
class create_carros(SuccessMessageMixin,CreateView):
    model=Carro
    form_class=CarroForm
    template_name='carros/carros-form-add.html'
    success_url=reverse_lazy('carros:list_cars')
    success_message = "%(modelo)s this was created successfully"


#
def create_carros_picture(request):

        if request.FILES['files']:
            file = request.FILES['files']
            fs = FileSystemStorage()  # defaults to   MEDIA_ROOT
            new_name = "picture"
            new_name = fs.get_valid_name(new_name)+".jpg"
            filename = fs.save(new_name, file)
            return JsonResponse({filename:file.name},safe=False)
        else:
            form=CarroForm()
            return render(request, "carros/carros-form-add.html",{'form':form})


def create_carros_warranty(request):
    if request.FILES['files']:
        file = request.FILES['files']
        fs = FileSystemStorage()  # defaults to   MEDIA_ROOT
        ext = file.name.split('.')[-1]
        new_name = "warranty"
        new_name = fs.get_valid_name(new_name) + '.' + ext
        filename = fs.save(new_name, file)
        return JsonResponse({filename: file.name}, safe=False)
    else:
        form = CarroForm()
        return render(request, "carros/carros-form-add.html", {'form': form})


class delete_carro(DeleteView):
    model = Carro
    success_url=reverse_lazy('carros:list_cars') 

def detail_invoices(request, pk):
    invoice=Invoices.objects.get(pk=pk)
    presupuesto=Presupuestos.objects.get(pk=invoice.estimate_id)
    return render(request, "carros/invoice-detail.html",
                  {'presupuesto': presupuesto})

SistemaCarros/carros/templates/carros/carro_confirm_delete.html
{% extends 'SistemaCarros/base.html' %}
{% load widget_tweaks %}



{% block content %}




            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">

                <div class="page-content">
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12 mb-3">
                                <div class="page-title-box d-flex align-items-center justify-content-between">
                                    <h4 class="mb-0">Vehicles</h4>

                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="{% url 'dashboard:dashboard' %}">Dashboard</a></li>
                                            <li class="breadcrumb-item active">Vehicles</li>
                                        </ol>
                                    </div>

                                </div>
                            </div>



                        </div>
                        <!-- end page title -->


                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">



                                        <form method="post">
                                            {% csrf_token %}
                                            <p>Are you sure you want to delete "{{ carro.placas }} {{ carro.modelo }}"?</p>
                                            <button class="btn btn-danger mb-3" type="submit">Delete</button>
                                        </form>



                                    </div>
                                </div>
                            </div> <!-- end col -->
                        </div> <!-- end row -->



                    </div> <!-- container-fluid -->
                </div>
                <!-- End Page-content -->
             </div>

{% endblock %}

SistemaCarros/carros/templates/carros/carros-detail.html
{% extends 'SistemaCarros/base.html' %}
{% load widget_tweaks %}



{% block content %}


            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">

                <div class="page-content">
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box d-flex align-items-center justify-content-between">
                                    <h4 class="mb-0">Vehicles</h4>

                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="{% url 'dashboard:dashboard' %}">The Shop</a></li>
                                            <li class="breadcrumb-item active">Vehicles</li>
                                        </ol>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <!-- end page title -->


                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">

                                        <h4><b>License plate:</b> {{ carros.placas }}</h4>
                                        <hr>
                                        <p><b>Model: </b>{{ carros.modelo }}</p>
                                        <p><b>Year: </b>{{ carros.año }}</p>
                                        <p><b>Make: </b>{{ carros.marca }}</p>
                                        <p><b>Type: </b>{{ carros.tipo }}</p>
                                        <p><b>VIN: </b>{{ carros.vin }}</p>
                                        <p><b>Color: </b>{{ carros.color }}</p>
                                        <p><b>Engine: </b>{{ carros.motor }}</p>
                                        <p><b>Insurance agent: </b>{{ carros.agente_seguros }}</p>
                                        <p><b>Insurance company: </b>{{ carros.compañia_seguros }}</p>
                                        <p><b>Policy No.: </b>{{ carros.no_politica }}</p>
                                        <p><b>Customer: </b>{{ carros.cliente }}</p>
                                        <div class="row mb-3">
                                            <div class="col-md-12">
                                                 <h4 class="card-title mb-3">Vehicle Picture</h4>
                                            </div>
                                        </div>
                                        {% load static %}
                                        <img src="{% get_media_prefix %}{{carros.new_name}}" height="68"/>
                                        <br>
                                        <div class="row mb-3">
                                                <div class="col-md-12">
                                                     <h4 class="card-title mb-3">Vehicle Warranty</h4>
                                                </div>
                                        </div>
                                        <img src="{% get_media_prefix %}{{carros.garantia_name}}" height="68" alt="No Picture"/>
                                        <br>

                                </div>

                            </div> <!-- end col -->

                        </div> <!-- end row -->



                    </div> <!-- container-fluid -->
                </div>
                <!-- End Page-content -->
            </div>

{% endblock %} 

SistemaCarros/carros/templates/carros/index.html
{% extends 'SistemaCarros/base.html' %}
{% load widget_tweaks %}
{% block content %}
<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="main-content">
<div class="page-content">
   <div class="container-fluid">
      <!-- start page title -->
      <div class="row">
         <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
               <h4 class="mb-0">Vehicles</h4>
               <div class="page-title-right">
                  <ol class="breadcrumb m-0">
                     <li class="breadcrumb-item"><a href="{% url 'dashboard:dashboard' %}">Dashboard</a></li>
                     <li class="breadcrumb-item active">Vehicles</li>
                  </ol>
               </div>
            </div>
         </div>
      </div>
      <!-- end page title -->
      <div class="row">
         <div class="col-12">
            <form method="post">
               {% csrf_token %}
               <div class="d-flex justify-content-between">
                  <a href="{% url 'carros:create_carros' %}"><button type="button" class="btn btn-success mb-3 waves-effect waves-light" onclick="addNewVehicle()">Add new</button></a>
                  <div class="col-md-6 mb-3 d-flex align-items-center justify-content-end">
                        <div class="span-container d-flex">
                           <input type="date" name="fromdate" class="form-control" data-date-inline-picker="true">
                           <input type="date" name="todate" class="form-control" data-date-inline-picker="true">
                           <input type="submit" value="Search" class="btn btn-secondary">
                           <!--                                                <input type="text" name="daterange" value="12/01/2021 - 12/31/2021" class="form-control" id="id_date_range"/>-->
                        </div>
                        <!--                                                <input type="text" name="daterange" value="12/01/2021 - 12/31/2021" class="form-control" id="id_date_range"/>-->
                     </div>
               </div>
               <div class="row">
                  <div class="col-12">
                     <div>
                        <div>
                           <div class="table-responsive mb-4">
                              {% if carros %}
                           <table class="table table-centered datatable dt-responsive nowrap table-card-list display" style="border-collapse: collapse; border-spacing: 0 12px; width: 100%;" id="datatable">
                              <thead>
                                 <tr class="bg-transparent">
                                    <th>Register since</th>
                                    <th data-priority="1">Gallery</th>
                                    <th data-priority="1">License plate</th>
                                    <th data-priority="1">Year</th>
                                    <th data-priority="3">Model</th>
                                    <th data-priority="3">Color</th>
                                    <th data-priority="3">Owner</th>
                                    <th data-priority="1">Actions</th>
                                 </tr>
                              </thead>
                              <tbody>
                              {% load static %}
                                 {% for carro in carros %}
                                 <tr>
                                    <td>{{carro.fecha_registros.date}}</td>
                                    {% if carro.new_name %}
                                    <td>
                                       <a data-id="{{carro.id}}" class="btn_view_gallery">
                                          <img src="{% get_media_prefix %}{{carro.new_name}}" height="68">
                                       </a>
                                    </td>
                                    {% else %}
                                    <td></td>
                                    {% endif %}
                                    <td>{{carro.placas}}</td>
                                    <td>{{carro.año}}</td>
                                    <td>{{carro.modelo}}</td>
                                    <td>{{carro.color}}</td>
                                    <td>{{carro.cliente.nombre}}</td>
                                    <td>
                                       <!--                                                                <a data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="uil-search-alt"></i></a>-->
                                       <a href="{% url 'carros:detail_carro' carro.id%}">Detail</a>
                                    </td>
                                    <td>
                                       <a href="{% url 'carros:edit_carros' carro.id%}">Edit</a>
                                    </td>
                                    <td>
                                       <a href="{% url 'carros:eliminar_carros' carro.id%}" class="text-danger" >Delete</a>
                                    </td>
                                 </tr>
                                 {% endfor %}
                              </tbody>
                           </table>
                              {% endif %}
                        </div>
                     </div>
                  </div>
               </div>
               </div>
            </form>
            </div>
            </div>
         </div>
         <!-- end col -->
      </div>
      <!-- end row -->
   </div>
   <!-- container-fluid -->
</div>
<!-- End Page-content -->
{% endblock %}

{% block script %}
<script>

   //View image gallery modal after clicking main image in car list
    var settings = {
            slidesPerView: 1,
            spaceBetween: 10,
            pagination: {
            el: ".swiper-pagination",
            clickable: true,
            },
            breakpoints: {
            640: {
                slidesPerView: 2,
                spaceBetween: 20,
            },
            768: {
                slidesPerView: 4,
                spaceBetween: 40,
            },
            1024: {
                slidesPerView: 5,
                spaceBetween: 50,
            },
            },
        };
     var swiper = new Swiper(".mySwiper", settings);

    $(document).ready(function () {
    $('.btn_view_gallery').on('click', function () {
        var id = $(this).data('id');

        $('#exampleModal').modal('show');
        $.ajax({
           url: 'image_detail',
           type: 'POST',
           data:{
             'id':id
           },
           success: function (res) {
              imgitems = JSON.parse(res);
              var content = "";
              for (item in imgitems){
                 content += " <div class=\"swiper-slide\"><img src=\"{%  get_media_prefix %}"+imgitems[item]+"\" height=\"68\" style='width: 222px; height: 222px' class='img-thumbnail'></div>"

              }

              $('.image-content').html(content);
               swiper.destroy();
               swiper = new Swiper(".mySwiper", settings);
           }
        })
    })
   })
</script>
{% endblock %} 